--CIDADES
INSERT INTO taxidb.cidade (`DESCRICAO`) 
	VALUES ('PATOS DE MINAS');
INSERT INTO taxidb.cidade (`DESCRICAO`) 
	VALUES ('LAGOA FORMOSA');
INSERT INTO taxidb.cidade (`DESCRICAO`) 
	VALUES ('PRESIDENTE OLEGARIO');
